### ISSUE TITLE
Events laden nicht

### ISSUE THREAD

**Issue by maximusvo** [Brandenburger-Maker/calendar-federation#7]
Keine Veranstaltungen werden aktuell geladen

**Comment by niccokunzmann** [comment]
Stimmt, der Fehler sieht so aus:

Irgendwo gibt es ein Event, das aufhört, bevor es anfängt.
Was soll man damit machen?

https://open-web-calendar.herokuapp.com/calendar.events.json?specification_url=https://raw.githubusercontent.com/Brandenburger-Maker/calendar-federation/master/calendar-configuration.json&timeshift=-120
```
Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/app/.heroku/python/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/app/.heroku/python/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/app/.heroku/python/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/app/.heroku/python/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/app/.heroku/python/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/app.py", line 229, in get_calendar
    entries = get_events(specification)
  File "/app/app.py", line 209, in get_events
    for events in events_list:
  File "/app/.heroku/python/lib/python3.7/concurrent/futures/_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "/app/.heroku/python/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/app/.heroku/python/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/app/.heroku/python/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/app.py", line 208, in 
    events_list = e.map(lambda url: retrieve_calendar(url, specification), urls)
  File "/app/app.py", line 166, in retrieve_calendar
    ical_events.extend(recurring_ical_events.of(calendar).between(one_year_before, one_year_ahead))
  File "/app/.heroku/python/lib/python3.7/site-packages/recurring_ical_events.py", line 204, in between
    if time_span_contains_event(span_start, span_stop, revent_start, revent_stop):
  File "/app/.heroku/python/lib/python3.7/site-packages/recurring_ical_events.py", line 55, in time_span_contains_event
    assert event_start <= event_stop, "the event must start before it ends"
AssertionError: the event must start before it ends
```

**Comment by niccokunzmann** [comment]
Die CoderDojo-Seite beinhaltet ein Event, das anfängt, nachdem es aufhört.

**Comment by niccokunzmann** [comment]
Es geht wieder. Ich habe das Event geändert. Danke!
